# Generated by Django 5.1.5 on 2026-04-01 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^09\\d{9}$')], verbose_name='mobile number'),
        ),
    ]
