# Generated by Django 5.1.5 on 2025-01-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.IntegerField(help_text='کد دسته بندی تماس')),
                ('title', models.CharField(help_text='عنوان دسته بندی تماس', max_length=128)),
                ('description', models.CharField(blank=True, help_text='توضیحات دسته بندی تماس', max_length=512, null=True)),
                ('callText', models.TextField(blank=True, help_text='متن تماس', null=True)),
                ('kind', models.SmallIntegerField(blank=True, choices=[(1, 'واردات'), (2, 'صادرات'), (3, 'داخلی'), (4, 'اپراتور'), (5, 'ادمین'), (6, 'بازاریابی'), (7, 'متفرقه')], null=True)),
                ('isActive', models.BooleanField(default=True, help_text='آیا دسته بندی تماس فعال است؟')),
                ('sendByNumber', models.SmallIntegerField(choices=[(1, '9124462808')], default=1, help_text='شماره خط جهت تماس')),
                ('delay_time', models.IntegerField(blank=True, default=0, help_text='if want the sms have some delay, must be set with minutes')),
                ('activeBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_receptor', models.CharField(blank=True, max_length=32, null=True)),
                ('params_message', models.TextField(blank=True, null=True)),
                ('params_sender', models.CharField(blank=True, max_length=32, null=True)),
                ('params_template', models.CharField(blank=True, max_length=32, null=True)),
                ('params_token', models.CharField(blank=True, max_length=32, null=True)),
                ('params_type', models.CharField(blank=True, max_length=32, null=True)),
                ('validation', models.BooleanField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'مخاطب در تماس دیگری است'), (2, 'اپلیکیشن توکن ارسال شده نامعتبر می باشد.'), (4, 'شناسه اپلیکیشن معتبر نمی باشد '), (5, 'شناسه تماس معتبر نیست '), (6, 'خطای نامشخص (Failed)'), (10, "مقدار پلتفرم کاربر نامعتبر می باشد. مقادیر معتبر : 'ios' یا 'android'"), (11, 'شناسه وارد شده تکراری می باشد (endpoint)'), (13, ' نوع پارامترها همخانی ندارد'), (14, 'دسترسی مجاز نیست'), (100, 'شناسه اپلیکیشن معتبر نمی باشد')], null=True)),
                ('messageid', models.BigIntegerField(null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=32, null=True)),
                ('receptor', models.CharField(blank=True, max_length=32, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_sending', models.BooleanField(default=True)),
                ('maxDuration', models.IntegerField(blank=True, null=True)),
                ('callCat', models.ForeignKey(blank=True, help_text='دسته بندی تماس', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_callCategory', to='notifications.callcategory')),
                ('send_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.IntegerField(help_text='کد دسته بندی پیامک')),
                ('title', models.CharField(help_text='عنوان دسته بندی پیامک', max_length=128)),
                ('description', models.CharField(blank=True, help_text='توضیحات دسته بندی پیامک', max_length=512, null=True)),
                ('smsText', models.TextField(blank=True, help_text='متن پیامک', null=True)),
                ('kind', models.SmallIntegerField(blank=True, choices=[(1, 'واردات'), (2, 'صادرات'), (3, 'داخلی'), (4, 'اپراتور'), (5, 'ادمین'), (6, 'بازاریابی'), (7, 'متفرقه')], null=True)),
                ('isActive', models.BooleanField(default=True, help_text='آیا دسته بندی پیامک فعال است؟')),
                ('sendByNumber', models.SmallIntegerField(choices=[(1, '100045312'), (2, '0018018949161'), (3, '10008663'), (4, '2000500666')], default=1, help_text='شماره خط جهت ارسال پیامک')),
                ('delay_time', models.IntegerField(blank=True, default=0, help_text='if want the sms have some delay, must be set with minutes')),
                ('activeBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_receptor', models.CharField(blank=True, max_length=32, null=True)),
                ('params_message', models.TextField(blank=True, null=True)),
                ('params_sender', models.CharField(blank=True, max_length=32, null=True)),
                ('params_template', models.CharField(blank=True, max_length=32, null=True)),
                ('params_token', models.CharField(blank=True, max_length=32, null=True)),
                ('params_type', models.CharField(blank=True, max_length=32, null=True)),
                ('validation', models.BooleanField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'در صف ارسال قرار دارد'), (2, 'زمان بندی شده (ارسال در تاریخ معین)'), (4, 'ارسال شده به مخابرات'), (5, 'ارسال شده به مخابرات (همانند وضعیت 4)'), (6, 'خطا در ارسال پیام که توسط سر شماره پیش می آید و به معنی عدم رسیدن پیامک می\u200cباشد (Failed)'), (10, 'رسیده به گیرنده (Delivered)'), (11, 'نرسیده به گیرنده ، این وضعیت به دلایلی از جمله خاموش یا خارج از دسترس بودن گیرنده اتفاق می افتد (Undelivered)'), (13, 'ارسال پیام از سمت کاربر لغو شده یا در ارسال آن مشکلی پیش آمده که هزینه آن به حساب برگشت داده می\u200cشود'), (14, 'بلاک شده است، عدم تمایل گیرنده به دریافت پیامک از خطوط تبلیغاتی که هزینه آن به حساب برگشت داده می\u200cشود'), (100, 'شناسه پیامک نامعتبر است ( به این معنی که شناسه پیام در پایگاه داده کاوه نگار ثبت نشده است یا متعلق به شما نمی\u200cباشد)')], null=True)),
                ('messageid', models.BigIntegerField(null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('sender', models.CharField(blank=True, max_length=32, null=True)),
                ('receptor', models.CharField(blank=True, max_length=32, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_sending', models.BooleanField(default=True)),
                ('send_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('smsCat', models.ForeignKey(blank=True, help_text='دسته بندی پیامک', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_smsCategory', to='notifications.smscategory')),
            ],
        ),
    ]
